#!/usr/bin/env bash
# save remote scrshot from adb
if [ "$#" -le 0 ]; then
  adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' | imgcat
else   
  adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > $@
fi
