#!/usr/bin/env bash

#cd $HOME/torrents/watch    # set your watch directory here
[[ "$1" =~ xt=urn:btih:([^&/]+) ]] || exit;
token="${BASH_REMATCH[1]}"
name="meta-$token"
echo "d10:magnet-uri${#1}:${1}e" > "$name.torrent"
rtorrent $name.torrent
rm "$name*" "$token"


