#!/usr/bin/env bash
py=`command -v python`
if [ -z "$py" ]; then py=`command -v python3`; fi

json_escape () {
    printf '%s' "$msg" | $py -c 'import json,sys; print(json.dumps(sys.stdin.read()))'
}
event=`cat ~/.nix/.notive > /dev/null 2>&1`
hostname=$(hostname)
msg="🐲 $hostname"

if [ ! -z "$1" ]; then
  msg="<b>$msg</b>: <pre>$1</pre>"
fi

if [ -z "$event" ]; then event="host $hostname"; fi

msg=$(json_escape)
json='{"auth":"nixifi3d","msg":'$msg',"event":"'$event'","mode":"html","tone":true}'
#echo $json
curl -d "$json" https://notive.j4hangir.com > /dev/null 2>&1
