#!/usr/bin/env bash
py=$(command -v python)
if [ -z "$py" ]; then py=$(command -v python3); fi

json_escape () {
    printf '%s' "$msg" | "$py" -c 'import json,sys; print(json.dumps(sys.stdin.read()))'
}
event=$(cat ~/.nix/.notive 2>/dev/null)
hostname=$(hostname)
msg="🐲 $hostname"

if [ ! -z "$1" ]; then
  msg="<b>$msg</b>: <pre>$1</pre>"
fi

if [ -z "$event" ]; then event="host $hostname"; fi

msg=$(json_escape)
auth="${NOTIVE_AUTH:-}"
if [ -z "$auth" ]; then
  echo "NOTIVE_AUTH not set" >&2
  exit 1
fi
json='{"auth":"'"$auth"'","msg":'"$msg"',"event":"'"$event"'","mode":"html","tone":true}'
#echo $json
curl -d "$json" https://notive.j4hangir.com > /dev/null 2>&1
