
set -g default-terminal "screen-256color"
set -g default-command /bin/zsh
set -g default-shell /bin/zsh

unbind C-b
set -g prefix C-u

# Dvorak-friendly pane navigation: h/t/n/s = left/down/up/right
setw -g mode-keys vi
unbind-key j
bind-key t select-pane -D
unbind-key k
bind-key h select-pane -L
unbind-key l
bind-key s select-pane -R

# New splits/windows inherit current path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Vi copy mode
bind Escape copy-mode
bind P paste-buffer
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "osc52copy"
bind-key -T copy-mode-vi 'r' send-keys -X rectangle-toggle

# Mouse
set-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M

set -g update-environment -r
set-option -g status-interval 1000

# Time messages remain in the status bar
set-option -g display-time 4000

bind-key r source-file ~/.tmux.conf \; display-message "Configuration reloaded"

# Pipe the current pane to a log file with Shift-H - Press Shift-H again to stop.
bind-key H pipe-pane -o "cat >>$HOME/#W-tmux.log" \; display-message "Toggled logging to $HOME/#W-tmux.log"

# Cycle panes
bind-key ` select-pane -t :.+

# Show url in buffer on osx
bind C-o run-shell "open $(tmux show-buffer)"

# Maximize and restore panes. Don't switch windows between using these :)
unbind Up
bind Up neww -d -n tmp \; swap-pane -s tmp.1 \; select-window -t tmp
unbind Down
bind Down last-window \; swap-pane -s tmp.1 \; kill-window -t tmp

# OSX Clipboard support
bind C-v run "tmux set-buffer $(reattach-to-user-namespace pbpaste); tmux paste-buffer"
bind C-c run "tmux save-buffer - | osc52copy"
